<?php
/**
 * Generated by "Autoload generator"
 * @link http://github.com/dmkuznetsov/php-autoloader
 * @date 2013-11-16 15:38
 */
function __dm_autoload_geo( $name )
{
	global $DOCUMENT_ROOT;
	$map = array (
  'Yandex\\Geo\\Api' => $DOCUMENT_ROOT.'/adwt/php_libs/php-yandex-geo-master/source/Yandex/Geo/Api.php',
  'Yandex\\Geo\\Exception' =>  $DOCUMENT_ROOT.'/adwt/php_libs/php-yandex-geo-master/source/Yandex/Geo/Exception.php',
  'Yandex\\Geo\\Exception\\CurlError' =>  $DOCUMENT_ROOT.'/adwt/php_libs/php-yandex-geo-master/source/Yandex/Geo/Exception/CurlError.php',
  'Yandex\\Geo\\Exception\\ServerError' =>  $DOCUMENT_ROOT.'/adwt/php_libs/php-yandex-geo-master/source/Yandex/Geo/Exception/ServerError.php',
  'Yandex\\Geo\\GeoObject' =>  $DOCUMENT_ROOT.'/adwt/php_libs/php-yandex-geo-master/source/Yandex/Geo/GeoObject.php',
  'Yandex\\Geo\\Response' =>  $DOCUMENT_ROOT.'/adwt/php_libs/php-yandex-geo-master/source/Yandex/Geo/Response.php',
);
	if ( isset( $map[ $name ] ) )
	{
		//echo $map[ $name ];
		require $map[ $name ];
	}
}
spl_autoload_register( '__dm_autoload_geo' );
