<?php
/**
 * Generated by "Autoload generator"
 * @link http://github.com/dmkuznetsov/php-autoloader
 * @date 2013-11-16 15:38
 */
function __dm_autoload_geo( $name )
{

	$map = array (
  'Yandex\\Geo\\Api' => dirname(__FILE__).'/source/Yandex/Geo/Api.php',
  'Yandex\\Geo\\Exception' =>  dirname(__FILE__).'/source/Yandex/Geo/Exception.php',
  'Yandex\\Geo\\Exception\\CurlError' =>  dirname(__FILE__).'/source/Yandex/Geo/Exception/CurlError.php',
  'Yandex\\Geo\\Exception\\ServerError' =>  dirname(__FILE__).'/source/Yandex/Geo/Exception/ServerError.php',
  'Yandex\\Geo\\GeoObject' =>  dirname(__FILE__).'/source/Yandex/Geo/GeoObject.php',
  'Yandex\\Geo\\Response' =>  dirname(__FILE__).'/source/Yandex/Geo/Response.php',
);
	if ( isset( $map[ $name ] ) )
	{
		require_once $map[ $name ];
	}
}
spl_autoload_register( '__dm_autoload_geo' );
